### ISSUE TITLE
Signing does not work when using variables in URL

### ISSUE THREAD

**Issue by ludwigm** [Nordstrom/artillery-plugin-aws-sigv4#13]
Hi,

I found out that the signing of the API calls does not work when using variables in your URL. I get 403 from the API Gateway that the Signature is wrong. More details can be found if the debug mode is switched on with setting `DEBUG=*` in front of your artillery run.

The API Gateway responses are the following:
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

When debugging it can be seen that `requestParams` only contains the original URL with the placeholder variable:
```
addAmazonSignatureV4: function(serviceName, requestParams, context, ee, callback) {
            var requetUrl = requestParams.uri || requestParams.url;
```

It seems that the templating and filling of variables is not done and the originally specified URL is used for signing which leads to a wrong signature.

Example config:
```
  config:
    plugins:
      aws-sigv4:
        serviceName: "execute-api"
    target: 'https://api.p.example.com/v1'
    defaults:
      headers: 
        x-api-key: 'sample'
    payload:
      path: "recentcontent.csv"
      fields:
        - contentId
    phases:
        - duration: 30
          arrivalRate: 1
  scenarios:
    - name: "Default test"
      beforeRequest: "addAmazonSignatureV4"
      flow:
      - log: "Current contentId is set to: {{ contentId }}"
      - get:
          url: "/example?configId=example&contentId={{ contentId }}"
```
